# -*- coding: utf-8 -*-
import json, re, unicodedata

# (name, type, address, hotline, thrombolysis, intervention, province)
ROWS = [
("Bệnh viện Tim mạch An Giang","Đơn vị Đột Quỵ","08 Nguyễn Du, P. Long Xuyên, Tỉnh An Giang","0296 3955357 / 0974 899775","Có","Không","An Giang"),
("Bệnh viện Đa khoa Châu Đốc","Khoa Can thiệp Tim mạch - Đột quỵ","917 Tôn Đức Thắng, P. Châu Đốc, Tỉnh An Giang","0296 3550705","Có","Có","An Giang"),
("Bệnh viện Đa khoa An Giang","Đơn vị Đột Quỵ","60 Ung Văn Khiêm, P. Long Xuyên, Tỉnh An Giang","0296 3910115","Có","Không","An Giang"),
("Bệnh viện Đa khoa Kiên Giang","Đơn vị Đột Quỵ","13 Nam Kỳ Khởi Nghĩa, P. Rạch Giá, Tỉnh An Giang","115 / 0297 3115","Có","Có","An Giang"),
("Trung Tâm Y Tế Giồng Riềng","Đơn vị Đột quỵ","Khu phố 8, xã Giồng Riềng, Tỉnh An Giang","0297 3822115","Có","Không","An Giang"),
("Bệnh viện Đa khoa Quốc tế Vinmec Phú Quốc","Đơn vị Đột quỵ","Khu bãi Dài, Đặc khu Phú Quốc, Tỉnh An Giang","0297 3985511","Có","Không","An Giang"),
("Bệnh viện Đa khoa Tân Châu","Đơn vị Đột Quỵ","485 Nguyễn Tri Phương, P. Tân Châu, Tỉnh An Giang","0296 3532726","Có","Không","An Giang"),
("Bệnh viện Quân Y 110","Đội đột quỵ","Số 7 Trần Lựu, phường Vũ Ninh","022 6261261","Có","Không","Bắc Ninh"),
("Bệnh viện Đa khoa Bắc Ninh số 2","Đội đột quỵ","Đường Nguyễn Quyền, phường Võ Cường","098 8365054","Có","Có","Bắc Ninh"),
("Bệnh viện Đa khoa Bắc Ninh số 1","Đội đột quỵ","Đường Lê Lợi, Phường Bắc Giang, Bắc Ninh","0204 8511551","Có","Không","Bắc Ninh"),
("Bệnh viện Đa khoa Bạc Liêu","Đơn vị Đột Quỵ","6 Nguyễn Huệ, P. Bạc Liêu, Tỉnh Cà Mau","115 / 0291 3115","Có","Không","Cà Mau"),
("Bệnh viện Đa khoa Thanh Vũ Medic Bạc Liêu","Đơn vị Đột Quỵ","02 DN, Đường tránh Quốc lộ 1A, khóm 1, P. Bạc Liêu, Tỉnh Cà Mau","1900 0115","Có","Không","Cà Mau"),
("Bệnh viện Đa khoa Cà Mau","Đơn vị Đột Quỵ","16 Hải Thượng Lãn Ông, Khóm 6, P. Hòa Thành, Tỉnh Cà Mau","0290 3832925","Có","Có","Cà Mau"),
("Bệnh viện Đa khoa Trung ương Cần Thơ","Khoa Đột quỵ","315 Nguyễn Văn Linh, P. Tân An, TP. Cần Thơ","090 7773184","Có","Có","Cần Thơ"),
("Bệnh viện Đột quỵ Tim mạch Cần Thơ (Bệnh viện Đa khoa Quốc Tế SIS Cần Thơ)","Trung tâm Đột quỵ","397 Nguyễn Văn Cừ, P. An Bình, TP. Cần Thơ","1800 1115","Có","Có","Cần Thơ"),
("Bệnh viện Đa khoa Hậu Giang","Đơn vị Đột Quỵ","Số 647 Trần Hưng Đạo, Khu vực 4, Phường Vị Thanh, TP. Cần Thơ","115 / 0293 3115","Có","Không","Cần Thơ"),
("Bệnh viện Hoàn Mỹ Cửu Long","Đơn vị Đột Quỵ","Lô 20 Võ Nguyên Giáp, P. Hưng Phú, TP. Cần Thơ","0292 3916916","Có","Có","Cần Thơ"),
("Bệnh viện Quân y 121","Khoa Nội Thần kinh - Đột quỵ","01 đường 30 tháng 04, Phường Ninh Kiều, TP. Cần Thơ","0292 3888121","Có","Không","Cần Thơ"),
("Bệnh viện Đa khoa Tỉnh Sóc Trăng","Khoa Nội Thần kinh - Đột quỵ","378 Đường Lê Duẩn, P. Phú Lợi, TP. Cần Thơ","088 8877115","Có","Có","Cần Thơ"),
("Bệnh viện Đà Nẵng","Khoa Đột quỵ","124 đường Hải Phòng, phường Hải Châu, TP. Đà Nẵng","0236 388521 / 089 8244555","Có","Có","Đà Nẵng"),
("Bệnh viện Đa khoa quốc tế Vinmec Đà Nẵng","Khoa đột quỵ","Đường 30/4, phường Hoà Cường, Đà Nẵng","094 1925115","Có","Có","Đà Nẵng"),
("Bệnh viện Đa khoa tỉnh Quảng Nam","Đội Đột quỵ","01 Nguyễn Du, phường Tam Kỳ, Đà Nẵng","0235 870115","Có","Có","Đà Nẵng"),
("Bệnh viện Đa khoa Trung ương Quảng Nam","Đội đột quỵ","Thôn Nam Sơn, xã Núi Thành, Đà Nẵng","090 5504988","Có","Có","Đà Nẵng"),
("Bệnh viện Đa khoa Khu vực miền núi phía Bắc Quảng Nam","Đơn vị Đột quỵ","107 Quang Trung, Đại Lộc, Đà Nẵng","0235 3865378 / 077 2555156","Có","Có","Đà Nẵng"),
("BV Đa khoa Khu Vực Quảng Nam","Đội đột quỵ","24 Lê Hữu Trác, phường Điện Bàn, Đà Nẵng","096 7931313","Có","Không","Đà Nẵng"),
("Bệnh viện Đa khoa Gia đình","Đơn vị Đột Quỵ","73 Nguyễn Hữu Thọ, Hải Châu, Đà Nẵng","0236 3632333","Có","Có","Đà Nẵng"),
("Bệnh viện 199","Đội Đột Quỵ","216 Nguyễn Công Trứ, An Hải, Đà Nẵng","0236 3986881","Có","Không","Đà Nẵng"),
("Bệnh viện Hoàn Mỹ Đà Nẵng","Đơn Vị Đột Quỵ","291 Nguyễn Văn Linh, Thanh Khê, Đà Nẵng","0236 3650950","Có","Không","Đà Nẵng"),
("Bệnh viện Đa khoa Vùng Tây Nguyên","Đội đột quỵ","184 Trần Quý Cáp, phường Buôn Ma Thuột, tỉnh Đắk Lắk","0262 3841649 (Khoa cấp cứu)","Có","Có","Đắk Lắk"),
("Bệnh viện đại học Y Dược Buôn Ma Thuột","Đội đột quỵ","298 Hà Huy Tập, Phường Buôn Ma Thuột, Đắk Lắk","1900 1147","Có","Không","Đắk Lắk"),
("Bệnh viện Đa khoa Phú Yên","Đội đột quỵ","15 Nguyễn Hữu Thọ, phường Tuy Hòa, tỉnh Đắk Lắk","083 4072347","Có","Không","Đắk Lắk"),
("Bệnh viện đa khoa Thiện Hạnh","Đơn vị đột quỵ","17 Nguyễn Chí Thanh, Tân An, Đắk Lắk","0262 3950606 / 115","Có","Có","Đắk Lắk"),
("Bệnh viện Đa khoa tỉnh Điện Biên","Đơn vị Đột Quỵ","Phường Mường Thanh, tỉnh Điện Biên","0215 3824008","Có","Không","Điện Biên"),
("Bệnh viện Đa khoa khu vực Long Khánh","Đơn vị Đột Quỵ","911 đường 21/4, Phường Bình Lộc, Đồng Nai","091 6677236","Có","Không","Đồng Nai"),
("Bệnh viện Đa khoa Thống Nhất – Đồng Nai","Đơn vị Đột Quỵ","234, quốc lộ 1, P. Long Bình, tỉnh Đồng Nai","0251 6516494","Có","Không","Đồng Nai"),
("Bệnh viện Đa khoa Đồng Nai","Đơn vị Đột Quỵ","02, Đồng Khởi, P. Tam Hiệp, Tỉnh Đồng Nai","091 7626115","Có","Có","Đồng Nai"),
("Bệnh viện Đa khoa khu vực Định Quán","Đơn vị Đột Quỵ","Ấp Hiệp Quyết, xã Định Quán, Tỉnh Đồng Nai","0251 3612003","Có","Không","Đồng Nai"),
("Bệnh viện Đa Khoa Bình Phước","Đơn vị Đột quỵ","QL14, Khu Tiến Thành 1, Phường Đồng Xoài, Đồng Nai","0271 3889047","Có","Không","Đồng Nai"),
("Bệnh viện Đa khoa Tiền Giang","Đơn vị Đột Quỵ","315 Quốc lộ 1A, KP Long Hưng, P. Phước Thạnh, Tỉnh Đồng Tháp","0273 3872363","Có","Không","Đồng Tháp"),
("Bệnh viện Đa khoa Đồng Tháp","Đơn vị Đột Quỵ","39 Nguyễn Văn Tre, P. Mỹ Ngãi, Tỉnh Đồng Tháp","0277 3899348","Có","Không","Đồng Tháp"),
("Bệnh viện Quân Y 120","Đội đột quỵ","Số 518 Nguyễn Thị Thập, P. Thới Sơn, Tỉnh Đồng Tháp","096 1120120","Có","Không","Đồng Tháp"),
("Bệnh viện Đa khoa Tâm Trí Đồng Tháp","Đơn vị Đột Quỵ","Số 700, Quốc Lộ 30, P. Mỹ Ngãi, Tỉnh Đồng Tháp","0277 3895115","Có","Không","Đồng Tháp"),
("Bệnh viện Đa khoa Sa Đéc","Đơn vị Đột Quỵ","153 Đ Nguyễn Sinh Sắc, khóm Hòa Khánh, P. Sa Đéc, Tỉnh Đồng Tháp","0277 3861918","Có","Không","Đồng Tháp"),
("Bệnh viện Đa khoa Tâm Trí Cao Lãnh","Đơn vị Đột quỵ","Số 1, đường Lê Thị Riêng, P. Cao Lãnh, Tỉnh Đồng Tháp","0277 3878115","Có","Không","Đồng Tháp"),
("Bệnh viện Đa khoa Gia Lai","Đội đột quỵ","132 Tôn Thất Tùng, phường Pleiku, tỉnh Gia Lai","0269 3824111","Có","Không","Gia Lai"),
("Bệnh viện Hoàng Anh Gia Lai","Đơn vị đột quỵ","238 Lê Duẩn, phường Hội Phú, Gia Lai","0269 2225225","Có","Không","Gia Lai"),
("Bệnh viện đa khoa trung tâm tỉnh Gia Lai","Khoa Thần Kinh - Đột quỵ","106 Nguyễn Huệ, phường Quy Nhơn, tỉnh Gia Lai","0256 3820775","Có","Có","Gia Lai"),
("Bệnh viện Bình Định","Đơn vị Thần kinh - Đột quỵ","39A Phạm Ngọc Thạch, phường Quy Nhơn, Gia Lai","1900 969639","Có","Không","Gia Lai"),
("Bệnh viện Bạch Mai","Trung Tâm Đột Quỵ","78 Giải Phóng, Phường Kim Liên, Thành phố Hà Nội","086 9587687","Có","Có","Hà Nội"),
("Bệnh viện Đa khoa Xanh Pôn","Đơn vị Đột Quỵ","12 Chu Văn An, Phường Ba Đình, Thành phố Hà Nội","098 6186606","Có","Có","Hà Nội"),
("Bệnh viện Đa khoa Đức Giang","Đơn vị Đột Quỵ","54 Trường Lâm, Phường Việt Hưng, Thành phố Hà Nội","037 5333115","Có","Có","Hà Nội"),
("Bệnh viện Đại học Y Hà Nội","Đơn vị Đột Quỵ","1 Tôn Thất Tùng, Phường Kim Liên, Thành phố Hà Nội","052 2115115","Có","Có","Hà Nội"),
("Bệnh viện E","Đơn vị Đột Quỵ","89 Trần Cung, Phường Nghĩa Đô, Thành phố Hà Nội","034 3454768","Có","Có","Hà Nội"),
("Bệnh viện Hữu Nghị Việt – Xô","Đội đột quỵ","1 Trần Khánh Dư, Phường Hai Bà Trưng, Thành phố Hà Nội","097 6431285","Có","Có","Hà Nội"),
("Bệnh viện Thanh Nhàn","Đơn vị Đột Quỵ","42 Thanh Nhàn, Phường Bạch Mai, Thành phố Hà Nội","024 39714363","Có","Có","Hà Nội"),
("Bệnh viện Trung ương Quân đội 108","Khoa Đột quỵ","1 Trần Hưng Đạo, Phường Hai Bà Trưng, Thành phố Hà Nội","024 62784156","Có","Có","Hà Nội"),
("Bệnh viện Quân Y 103","Khoa Đột quỵ","261 Phùng Hưng, Phường Hà Đông, Thành phố Hà Nội","024 62851616","Có","Có","Hà Nội"),
("Bệnh viện Hữu Nghị Việt Đức","Đơn vị Đột Quỵ","40 Tràng Thi, Phường Hoàn Kiếm, Thành phố Hà Nội","092 7515519","Có","Có","Hà Nội"),
("Bệnh viện Quân Y 105","Đơn vị Đột Quỵ","2 Chùa Thông, Phường Sơn Tây, Thành phố Hà Nội","032 7664105","Có","Có","Hà Nội"),
("Bệnh viện 19-8","Đơn vị Đột Quỵ","9 Trần Bình, Phường Từ Liêm, Thành phố Hà Nội","093 7527700","Có","Có","Hà Nội"),
("Bệnh viện Tim Hà Nội cơ sở 1","Đơn vị Đột quỵ","92 Trần Hưng Đạo, Phường Cửa Nam, Thành phố Hà Nội","096 3091746","Có","Có","Hà Nội"),
("Bệnh viện Lão Khoa Trung Ương","Đơn vị đột quỵ","Số 1A Phương Mai, P. Kim Liên, TP. Hà Nội","096 4158939","Có","Không","Hà Nội"),
("Bệnh viện Bưu Điện CS1","Đội đột quỵ","49 Trần Điền, Phường Phương Liệt, Thành phố Hà Nội","1800 6090","Có","Không","Hà Nội"),
("Bệnh viện Đa Khoa Tâm Anh Hà Nội","Đơn vị đột quỵ","108 Đường Hoàng Như Tiếp, Phường Bồ Đề, TP. Hà Nội","024 71066858 / 024 38723872","Có","Có","Hà Nội"),
("Bệnh viện Đa Khoa Vân Đình","Đơn vị đột quỵ","Số 1 Thanh Ấm, Xã Vân Đình, TP. Hà Nội","1900 571238","Có","Không","Hà Nội"),
("Bệnh viện Đa Khoa Nông Nghiệp","Đơn Vị Đột Quỵ","Km 13+500 Quốc lộ 1A, Xã Ngọc Hồi, Thành phố Hà Nội","096 7781616","Có","Không","Hà Nội"),
("Bệnh viện Đa khoa tỉnh Hà Tĩnh","Đơn vị Đột Quỵ","75 Hải Thượng Lãn Ông, Phường Thành Sen, Hà Tĩnh","0239 3699115","Có","Không","Hà Tĩnh"),
("Trung Tâm Y Tế Thành Sen","Đơn vị Đột Quỵ","456 Hải Thượng Lãn Ông, Phường Thành Sen, Hà Tĩnh","091 2606395 / 096 9118111","Có","Không","Hà Tĩnh"),
("Bệnh viện Đa Khoa Thị Xã Kỳ Anh","Đơn vị Đột quỵ","Số 534, đường Lê Đại Hành, TDP Hưng Hoà, Phường Sông Trí, Tỉnh Hà Tĩnh","0239 3966028","Có","Không","Hà Tĩnh"),
("Bệnh viện Hữu Nghị Việt Tiệp","Khoa Đột quỵ","Số 1 Nhà thương, phường Lê Chân","086 7696232","Có","Có","Hải Phòng"),
("Bệnh viện Kiến An","Đội đột quỵ","35 Trần Tất Văn, phường Phù Liễn","086 8505722","Có","Không","Hải Phòng"),
("Bệnh viện Quân Y 7","Đơn vị đột quỵ","12 Tuệ Tĩnh, Hải Dương, TP. Hải Phòng","0220 6255135","Có","Không","Hải Phòng"),
("Bệnh viện đa khoa quốc tế Vinmec Hải Phòng","Đội đột quỵ","Tổ 31, P. An Biên, TP. Hải Phòng","0225 7309888","Có","Không","Hải Phòng"),
("Bệnh viện đa khoa quốc tế Hải Phòng","Đơn vị đột quỵ","124 Nguyễn Đức Cảnh, Lê Chân, Hải Phòng","0225 3955888","Có","Không","Hải Phòng"),
("Bệnh viện Đa khoa Hải Dương","Khoa Đột quỵ","225 Nguyễn Lương Bằng, phường Lê Thanh Nghị","0220 3895115","Có","Có","Hải Phòng"),
("Bệnh viện Đa khoa Khu vực Củ Chi","Đơn vị đột quỵ","Số 9A Đường Nguyễn Văn Hoài, Ấp Bàu Tre 2B, Xã Tân An Hội, TP.HCM","028 38920475","Có","Không","Hồ Chí Minh"),
("Bệnh viện Đa khoa Hoàn Mỹ Sài Gòn","Đơn vị Đột Quỵ","60-60A Phan Xích Long, P. Cầu Kiệu, TP.HCM","028 39959860","Có","Có","Hồ Chí Minh"),
("Bệnh viện Đa khoa Xuyên Á TP.HCM","Đơn vị đột quỵ","Số 42 Quốc lộ 22, Ấp Chợ, xã Tân Phú Trung, TP.HCM","028 37966999","Có","Có","Hồ Chí Minh"),
("Bệnh viện Đại học Y Dược TP.HCM","Đơn vị đột quỵ","215 Hồng Bàng, Phường Chợ Lớn, TP.HCM","028 39525115 / 028 39525165","Có","Có","Hồ Chí Minh"),
("Bệnh viện Nhân Dân 115","Trung tâm Đột Quỵ","527 Sư Vạn Hạnh, Phường Hoà Hưng, TP.HCM","028 38650514 / 096 7701010","Có","Có","Hồ Chí Minh"),
("Bệnh viện Nhân Dân Gia Định","Đơn vị đột quỵ","1 Nơ Trang Long, Phường Gia Định, TP.HCM","028 38412692 (Ext 211)","Có","Có","Hồ Chí Minh"),
("Bệnh viện Nguyễn Tri Phương","Đơn vị đột quỵ","468 Nguyễn Trãi, P. An Đông, TP.HCM","028 68566115 / 094 9714386","Có","Có","Hồ Chí Minh"),
("Bệnh viện Thống Nhất","Đơn vị đột quỵ","1 Lý Thường Kiệt, Phường Tân Sơn Nhất, TP.HCM","028 38640261","Có","Có","Hồ Chí Minh"),
("Bệnh viện Quân Y 175","Đơn vị Đột Quỵ","786 Nguyễn Kiệm, P. Hạnh Thông, TP.HCM","096 8115175","Có","Có","Hồ Chí Minh"),
("Bệnh viện Lê Văn Thịnh","Đơn vị Đột Quỵ","130 Lê Văn Thịnh, P. Bình Trưng Tây, TP.HCM","028 54327888 (Ext 0)","Có","Không","Hồ Chí Minh"),
("Bệnh viện Thủ Đức","Đơn vị Đột Quỵ","29 Phú Châu, Phường Tam Bình, TP.HCM","028 22153115","Có","Có","Hồ Chí Minh"),
("Bệnh viện Đa khoa khu vực Thủ Đức","Đơn vị Đột Quỵ","64 Lê Văn Chí, Phường Linh Trung, TP.HCM","028 38966894","Có","Có","Hồ Chí Minh"),
("Bệnh viện Gia An 115","Đơn vị Đột Quỵ","05 đường số 17A, Khu phố 11, P. An Lạc, TP.HCM","028 62655115","Có","Có","Hồ Chí Minh"),
("Bệnh viện Bình Tân","Đội đột quỵ","809 Hương Lộ 2, P. Bình Trị Đông, TP.HCM","028 37541785","Có","Không","Hồ Chí Minh"),
("Bệnh viện Nguyễn Trãi","Đơn vị Đột Quỵ","314 Nguyễn Trãi, P. An Đông, TP.HCM","028 39248158 (Ext 440)","Có","Không","Hồ Chí Minh"),
("Bệnh viện An Bình","Đơn vị Đột Quỵ","146 An Bình, P. An Đông, TP.HCM","028 39237986 (Ext 5156)","Có","Không","Hồ Chí Minh"),
("Bệnh viện Hóc Môn","Đơn vị đột quỵ","79 đường Bà Triệu, Xã Hóc Môn, TP.HCM","083 7101445 / 033 2085612","Có","Không","Hồ Chí Minh"),
("Bệnh viện Vạn Hạnh","Đội đột quỵ","700 Sư Vạn Hạnh, P. Hoà Hưng, TP.HCM","028 38632553","Có","Có","Hồ Chí Minh"),
("Bệnh viện Đa khoa Lãnh Binh Thăng","Đơn vị Đột quỵ","72 đường số 5, phường Bình Thới, TP.HCM","090 9971643","Có","Không","Hồ Chí Minh"),
("Bệnh viện Đa khoa Bình Dương","Đơn vị Đột Quỵ","Phạm Ngọc Thạch, Phường Phú Lợi, TP.HCM","0274 3822107","Có","Không","Hồ Chí Minh"),
("Bệnh viện Vũng Tàu","Đơn vị Đột Quỵ","Số 27, đường 2/9, phường Phước Thắng, TP.HCM","093 4630708","Có","Không","Hồ Chí Minh"),
("Bệnh viện Bà Rịa","Đơn vị Đột Quỵ","686 Võ Văn Kiệt, P. Tam Long, TP.HCM","115","Có","Không","Hồ Chí Minh"),
("Bệnh viện Đa khoa Thái Bình","Đơn vị Đột quỵ","530 Lý Bôn, phường Trần Hưng Đạo, Hưng Yên","096 9831212","Có","Không","Hưng Yên"),
("Bệnh viện Đa khoa Phố Nối","Đơn vị Đột Quỵ","36 Đường Vũ Văn Cẩn, Phường Mỹ Hào, Hưng Yên","0221 6334666","Có","Không","Hưng Yên"),
("Bệnh viện Đột quỵ và Thần kinh Hà Nội - Thái Bình","Đơn vị đột quỵ","Số 1 Nguyễn Tông Quai, P. Trần Lãm, Hưng Yên","032 8112115","Có","Có","Hưng Yên"),
("Bệnh viện Đa khoa Tỉnh Hưng Yên","Đơn Vị Đột Quỵ","Đường Hải Thượng Lãn Ông, phường Phố Hiến","096 6331515","Có","Không","Hưng Yên"),
("Bệnh viện Đa khoa Ninh Thuận","Đơn vị Đột Quỵ","Nguyễn Văn Cừ, phường Ninh Chữ, tỉnh Khánh Hoà","0259 3822666","Có","Không","Khánh Hòa"),
("Bệnh viện Đa khoa tỉnh Khánh Hòa","Khoa đột quỵ","19 Yersin, phường Nha Trang, Khánh Hoà","091 1874930","Có","Không","Khánh Hòa"),
("Bệnh viện đa khoa tỉnh Lạng Sơn","Đội đột quỵ","Khối Đại Sơn, Phường Kỳ Lừa, Lạng Sơn","0205 3898115","Có","Không","Lạng Sơn"),
("Bệnh viện Đa Khoa số 2 tỉnh Lào Cai","Đơn vị Đột Quỵ","Đường Võ Nguyên Giáp, Phường Cam Đường, Tỉnh Lào Cai","0214 3758993","Có","Không","Lào Cai"),
("Trung Tâm Y Tế Khu Vực Văn Yên","Đơn vị Đột Quỵ","Xã Mậu A, tỉnh Lào Cai","083 3281033","Có","Không","Lào Cai"),
("Bệnh viện Đa Khoa số 1 tỉnh Lào Cai","Đơn vị Đột Quỵ","Thôn Tiền Phong, Phường Âu Lâu, Tỉnh Lào Cai","091 1241313","Có","Có","Lào Cai"),
("Trung tâm Y tế khu vực Yên Bình","Đơn vị Đột Quỵ","Thôn Thanh Bình, Xã Phú Thịnh, Tỉnh Lào Cai","098 5411115","Có","Không","Lào Cai"),
("Bệnh viện Đa khoa An Phước","Đội đột quỵ","Số 235 Trần Phú, phường Phan Thiết, tỉnh Lâm Đồng","0252 3831056","Có","Không","Lâm Đồng"),
("Bệnh viện Đa khoa tỉnh Lâm Đồng","Đơn vị Đột Quỵ","01 Phạm Ngọc Thạch, Phường Cam Ly, Đà Lạt, tỉnh Lâm Đồng","115","Có","Có","Lâm Đồng"),
("Bệnh viện II Lâm Đồng","Đơn vị Đột Quỵ","263 Trần Quốc Toản, Phường B'lao, Tỉnh Lâm Đồng","026 3386 4311","Có","Không","Lâm Đồng"),
("Bệnh viện Hoàn Mỹ Đà Lạt","Đội đột quỵ","Đồi Long Thọ, Phường Xuân Hương, Đà Lạt, tỉnh Lâm Đồng","026 3351 0878","Có","Không","Lâm Đồng"),
("Bệnh viện Đa Khoa Bình Thuận","Đơn vị đột quỵ","Đường Tôn Thất Bách, phường Bình Thuận, tỉnh Lâm Đồng","0252 3822 733","Có","Không","Lâm Đồng"),
("Bệnh viện Đa khoa tỉnh Ninh Bình","Khoa Đột Quỵ","80 Tuệ Tĩnh, Phường Hoa Lư, Tỉnh Ninh Bình","094 2265115","Có","Có","Ninh Bình"),
("Bệnh viện Hải Hậu","Đơn Vị Đột Quỵ","Số 236, Thôn 3 Yên Định, Xã Hải Hậu, Tỉnh Ninh Bình","0228 3877147","Có","Không","Ninh Bình"),
("Bệnh viện đa khoa Hà Nam","Đội đột quỵ","Trường Chinh, Chân Cầu, Phủ Lý, Ninh Bình","0226 3850611","Có","Không","Ninh Bình"),
("Bệnh viện Đa khoa Nam Định","Đội đột quỵ","Khu đô thị Mỹ Trung, Phường Thiên Trường, tỉnh Ninh Bình","085 7911911","Có","Không","Ninh Bình"),
("Bệnh viện Hữu nghị đa khoa Nghệ An","Trung Tâm Đột Quỵ","Km số 5, VI Lê Nin, xóm 14, Vinh, Nghệ An","096 8623337","Có","Có","Nghệ An"),
("Bệnh viện Đa Khoa Thành Phố Vinh Cơ Sở 1","Đơn vị Đột Quỵ","178 Trần Phú, Phường Trường Vinh, Nghệ An","032 5203589","Có","Không","Nghệ An"),
("Bệnh viện Đa Khoa Thành Phố Vinh Cơ Sở 2","Đơn vị Đột Quỵ","31 Lê Ninh, Phường Vinh Hưng, Nghệ An","1900 9218","Có","Không","Nghệ An"),
("Bệnh viện Đa Khoa Hòa Bình","Đơn vị Đột Quỵ","Phường Hoà Bình, Tỉnh Phú Thọ","115 / 0218 3896546 (ext 117)","Có","Không","Phú Thọ"),
("Bệnh viện Đa khoa Vĩnh Phúc","Đơn vị Đột Quỵ","1 Tôn Thất Tùng, Phường Vĩnh Phúc, Tỉnh Phú Thọ","0211 3696311","Có","Có","Phú Thọ"),
("Bệnh viện Đa khoa tỉnh Phú Thọ","Trung Tâm Đột Quỵ","Đường Nguyễn Tất Thành, Phường Việt Trì, Tỉnh Phú Thọ","0210 6552288","Có","Có","Phú Thọ"),
("Trung tâm Y tế khu vực Tam Nông","Đơn vị Đột Quỵ","Khu 24, Xã Vạn Xuân, Tỉnh Phú Thọ","1800 969629 / 032 6663535","Có","Không","Phú Thọ"),
("Trung tâm Y tế khu vực Thanh Thủy","Đơn vị Đột Quỵ","Khu 5, Xã Thanh Thuỷ, Tỉnh Phú Thọ","1800 969666","Có","Không","Phú Thọ"),
("Bệnh viện Đa Khoa Phúc Yên","Đơn vị đột quỵ","Ngõ 10, đường Hai Bà Trưng, Phường Phúc Yên, Tỉnh Phú Thọ","028 62934226","Có","Không","Phú Thọ"),
("Trung tâm Y tế khu vực Tân Sơn","Đơn vị đột quỵ","Khu 5B, Xã Tân Sơn, Tỉnh Phú Thọ","1800 969677","Có","Không","Phú Thọ"),
("Trung tâm Y tế khu vực Cẩm Khê","Đơn vị đột quỵ","147 Hoa Khê, Xã Cẩm Khê, Tỉnh Phú Thọ","1800 8262","Có","Không","Phú Thọ"),
("Trung tâm Y tế khu vực Lâm Thao","Đơn vị đột quỵ","Phố Nguyễn Mẫn Đốc, Khu Lâm Thao, Xã Lâm Thao, Tỉnh Phú Thọ","1800 969656","Có","Không","Phú Thọ"),
("Bệnh viện Đa khoa tỉnh Quảng Ninh","Đơn vị Đột Quỵ","Phố Tuệ Tĩnh, Phường Hồng Gai, Quảng Ninh","0203 3825486","Có","Có","Quảng Ninh"),
("Bệnh viện Bãi Cháy","Đội đột quỵ","Phường Việt Hưng, Quảng Ninh","091 5289866","Có","Không","Quảng Ninh"),
("Bệnh viện Việt Nam – Thuỵ Điển Uông Bí","Đơn vị Đột Quỵ","Đường Tuệ Tĩnh, Phường Uông Bí, Quảng Ninh","0203 3854279","Có","Không","Quảng Ninh"),
("Bệnh viện đa khoa Cẩm Phả","Đội đột quỵ","371 Trần Phú, Phường Cẩm Phả","0203 3862566","Có","Không","Quảng Ninh"),
("Bệnh viện đa khoa khu vực Cẩm Phả","Đội đột quỵ","Tổ 1 khu 3, phường Cửa Ông, tỉnh Quảng Ninh","096 6341313 / 091 3989826","Có","Không","Quảng Ninh"),
("Bệnh viện đa khoa Cẩm Phả (CS2)","Đội đột quỵ","371 Trần Phú, Cẩm Phả, Quảng Ninh","096 5361313","Có","Không","Quảng Ninh"),
("Trung tâm Y tế Hải Hà","Đội đột quỵ","10 Trần Quốc Toản, Quảng Hà, Hải Hà, Quảng Ninh","096 6311313","Có","Không","Quảng Ninh"),
("Bệnh viện đa khoa quốc tế Vinmec Hạ Long","Đội đột quỵ","10A Lê Thánh Tông, Hạ Long, Quảng Ninh","0203 3828188","Có","Không","Quảng Ninh"),
("BV Đa khoa Tỉnh Quảng Ngãi","Đội đột quỵ","Đường Lê Hữu Trác, phường Nghĩa Lộ, Quảng Ngãi","0255 3828642","Có","Không","Quảng Ngãi"),
("Bệnh viện đa khoa tỉnh Quảng Ngãi 2","Đội đột quỵ","224 Bà Triệu, Phường Kon Tum, tỉnh Quảng Ngãi","0260 3862572","Có","Không","Quảng Ngãi"),
("Bệnh viện Hữu Nghị Việt Nam – Cu Ba Đồng Hới","Đội đột quỵ","TDP 10, Nam Lý, Đồng Hới, Quảng Trị","098 8888148","Có","Có","Quảng Trị"),
("Bệnh viện Đa khoa Khu vực Bắc Quảng Trị","Đội đột quỵ","TDP Minh Phượng, Phường Bắc Gianh, Tỉnh Quảng Trị","094 6950001","Có","Không","Quảng Trị"),
("Bệnh viện Đa khoa tỉnh Quảng Trị","Đơn vị đột quỵ","266 Hùng Vương, Nam Đông Hà, Quảng Trị","091 9952085","Có","Có","Quảng Trị"),
("Bệnh viện Đa khoa tỉnh Sơn La","Đơn vị Đột Quỵ","Tổ 17, phường Chiềng Sinh, tỉnh Sơn La","0212 3753373","Có","Không","Sơn La"),
("Bệnh viện Đa Khoa Khu Vực Vân Hồ","Đơn vị Đột Quỵ","TDP Bình Nguyên, Phường Thảo Nguyên, tỉnh Sơn La","0212 3869115 / 032 5348115","Có","Không","Sơn La"),
("Bệnh viện Đa Khoa Long An","Đơn vị đột quỵ","211 Nguyễn Thông, Phường Long An, Tỉnh Tây Ninh","0272 3826330","Có","Không","Tây Ninh"),
("Bệnh viện Xuyên Á Tây Ninh","Đơn vị đột quỵ","Số 10 Xuyên Á, khu phố Trâm Vàng 3, phường Gò Dầu, tỉnh Tây Ninh","0276 3762999","Có","Có","Tây Ninh"),
("Bệnh viện Đa Khoa Hồng Hưng","Đơn vị Đột quỵ","187 Phạm Văn Đồng, khu phố Hiệp Long, phường Thanh Điền, tỉnh Tây Ninh","0276 3836991","Có","Không","Tây Ninh"),
("Bệnh viện Xuyên Á Long An","Đơn vị đột quỵ","QLN2, Hậu Nghĩa, Đức Hoà, Tây Ninh","0272 3649999","Có","Có","Tây Ninh"),
("Bệnh viện Đa khoa Tây Ninh","Đơn vị đột quỵ","626 Đường 30 tháng 4, KP 5, phường Tân Ninh, tỉnh Tây Ninh","0276 3822145","Có","Không","Tây Ninh"),
("Bệnh viện đa khoa tỉnh Tuyên Quang","Đội đột quỵ","Số 44, đường Lê Duẩn, phường Minh Xuân, tỉnh Tuyên Quang","0207 3922132","Có","Không","Tuyên Quang"),
("Bệnh viện Đa khoa Đức Minh","Đơn vị Đột Quỵ","Nguyễn Du, Phường Hà Giang 1, Tuyên Quang","086 9864115","Có","Không","Tuyên Quang"),
("Bệnh viện Đa Khoa Hà Giang","Đơn vị Đột quỵ","Số 11, tổ 10, Phường Hà Giang 2, tỉnh Tuyên Quang","0219 386641","Có","Có","Tuyên Quang"),
("Bệnh viện Đa Khoa Khu Vực Đồng Văn","Đơn vị Đột quỵ","Thôn Thành Tâm, Xã Đồng Văn, Tuyên Quang","096 5311717","Có","Không","Tuyên Quang"),
("Bệnh viện Đa Khoa Khu Vực Quang Bình","Đơn vị Đột quỵ","Tổ 5, xã Quang Bình, Tuyên Quang","096 5281717","Có","Không","Tuyên Quang"),
("Bệnh viện Đa Khoa Khu Vực Vị Xuyên","Đơn vị Đột quỵ","Tổ 10, xã Vị Xuyên, Tuyên Quang","094 9285926","Có","Không","Tuyên Quang"),
("Bệnh viện Đa Khoa Khu Vực Hoàng Su Phì","Đơn vị Đột quỵ","Thôn 3, Xã Hoàng Su Phì, Tuyên Quang","0219 3831413","Có","Không","Tuyên Quang"),
("Bệnh viện Trung ương Thái Nguyên","Trung Tâm Đột Quỵ","479 Lương Ngọc Quyến, Phường Phan Đình Phùng, Tỉnh Thái Nguyên","0208 3857378","Có","Có","Thái Nguyên"),
("Bệnh viện đa khoa tỉnh Bắc Kạn","Đội đột quỵ","Tổ 4, P. Đức Xuân, Thái Nguyên","096 6631919","Có","Không","Thái Nguyên"),
("Bệnh viện Gang Thép Thái Nguyên","Đội đột quỵ","Đường Vó Ngựa, Phường Tích Lương, Tỉnh Thái Nguyên","0208 3832255","Có","Không","Thái Nguyên"),
("Bệnh viện Đa khoa tỉnh Thanh Hoá","Đơn vị Đột Quỵ","181 Hải Thượng Lãn Ông, Phường Hạc Thành, Tỉnh Thanh Hoá","0237 3950303","Có","Có","Thanh Hoá"),
("Bệnh viện Đa khoa Hợp Lực","Đơn vị Đột Quỵ","595 Nguyễn Chí Thanh, Phường Đông Thọ, Tỉnh Thanh Hóa","0237 3713777","Có","Không","Thanh Hoá"),
("Bệnh viện Đa Khoa Nghi Sơn","Đơn vị Đột Quỵ","TDP Xuân Hoà, Phường Tĩnh Gia, Tỉnh Thanh Hoá","036 9852535","Có","Không","Thanh Hoá"),
("Bệnh viện Đa Khoa Ngọc Lặc","Đơn Vị Đột Quỵ","QL15 Ngọc Lặc, Thanh Hoá","0237 3871146","Có","Không","Thanh Hoá"),
("Bệnh viện Đa khoa Thọ Xuân","Đơn vị Đột Quỵ","Thôn Nam Xuân, Xã Thọ Xuân, Tỉnh Thanh Hoá","0237 3538538","Có","Không","Thanh Hóa"),
("Bệnh viện Trung ương Huế cơ sở 2","Đội đột quỵ","Tổ dân phố Thượng An 2, phường Phong Thái, TP. Huế","0234 3761761 (số máy lẻ 1515)","Có","Có","Thừa Thiên Huế"),
("Bệnh viện Trung ương Huế","Trung tâm Đột quỵ","16 Lê Lợi, Thuận Hoá, Thành phố Huế","094 9024115","Có","Có","Thừa Thiên Huế"),
("Bệnh viện Nguyễn Đình Chiểu","Đơn vị Đột Quỵ","109 Đoàn Hoàng Minh, phường An Hội, tỉnh Vĩnh Long","0275 3817555","Có","Không","Vĩnh Long"),
("Bệnh viện Đa khoa Vĩnh Long","Đơn vị Đột Quỵ","301 Trần Phú, P. Phước Hậu, Tỉnh Vĩnh Long","0270 3823520","Có","Không","Vĩnh Long"),
("Bệnh viện Đa khoa Xuyên Á Chi nhánh Vĩnh Long","Đơn vị Đột Quỵ","68E Phạm Hùng, P. Long Châu, Tỉnh Vĩnh Long","0270 6250999 / 0270 6250888","Có","Có","Vĩnh Long"),
("Bệnh viện Đa khoa Trà Vinh","Đơn vị Đột Quỵ","399, Nguyễn Đáng, P. Nguyệt Hoá, Tỉnh Vĩnh Long","115 / 0294 3115","Có","Không","Vĩnh Long"),
]

def slugify(text):
    nfkd = unicodedata.normalize('NFKD', text)
    ascii_text = nfkd.encode('ascii', 'ignore').decode('ascii')
    ascii_text = ascii_text.replace('Đ', 'D').replace('đ', 'd')
    slug = re.sub(r'[^a-zA-Z0-9]+', '-', ascii_text).strip('-').lower()
    return slug

records = []
seen_ids = {}
for (name, typ, addr, hotline, throm, interv, province) in ROWS:
    base_id = slugify(f"{name}-{province}")
    n = seen_ids.get(base_id, 0)
    seen_ids[base_id] = n + 1
    entry_id = base_id if n == 0 else f"{base_id}-{n+1}"
    records.append({
        "id": entry_id,
        "name": name,
        "type": typ,
        "province": province,
        "address": addr,
        "hotline": hotline,
        "thrombolysis": throm,   # BV có tiêu sợi huyết
        "intervention": interv,  # BV có can thiệp
        "status": "active",
        "updatedAt": "2025-09",
        "source": "Hội Đột Quỵ Việt Nam (VNSA)",
    })

# Chuẩn hoá lỗi chính tả trong PDF gốc: "Thanh Hóa" và "Thanh Hoá" là cùng 1 tỉnh
for r in records:
    if r["province"] in ("Thanh Hóa",):
        r["province"] = "Thanh Hoá"

print(f"Tổng số bản ghi: {len(records)}")
assert len(records) == 170, f"Số dòng không khớp: {len(records)}"

with open('/home/claude/repo/data/hospitals.json', 'w', encoding='utf-8') as f:
    json.dump(records, f, ensure_ascii=False, indent=2)

print("Đã ghi data/hospitals.json")
